/** Supported chart type keys — rosencharts + shadcn */
export const CHART_TYPE_KEYS = [
  "horizontal-bar",
  "horizontal-bar-gradient",
  "horizontal-bar-multi",
  "horizontal-bar-image",
  "horizontal-bar-thin",
  "vertical-bar",
  "vertical-bar-multi",
  "line",
  "line-multi",
  "pie",
  "pie-image",
  "donut",
  "half-donut",
  "fillable",
  "fillable-donut",
  "breakdown",
  "breakdown-thin",
  "benchmark",
  "treemap",
  "scatter",
  "shadcn:bar",
  "shadcn:area",
  "shadcn:line",
  "shadcn:pie",
  "shadcn:radar",
  "shadcn:radial",
] as const;

export type ChartTypeKey = (typeof CHART_TYPE_KEYS)[number];
